name: 'deploy for tencentyun'

on:
  workflow_dispatch:
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2

    - name: 配置用户信息并检查有效性
      run: echo '${{ secrets.biliconfig }}' > ./config/config.json && python3 check.py
      
    - name: 安装ServerlessFramework
      run: sudo npm install -g serverless
    
    - name: 部署至腾讯云
      run: sls deploy --debug
      env:
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
